apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240307094416.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240307094416.0.0+build.6aff574
  releaseNotes: |
    Release v20240307094416.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-06-03-2024-22-30-17-452362674/where-for-dinner-my-apps-bundle@sha256:fc70e780ef8df330894e37267c1fd6cf9b9dbe87007fd452e2f6cb54f4cc5a5f
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

