apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20240307094440.0.0+build.6aff574
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20240307094440.0.0+build.6aff574
  releaseNotes: |
    Release v20240307094440.0.0+build.6aff574 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-06-03-2024-22-30-17-452362674/where-for-dinner-search-proc-my-apps-bundle@sha256:cc626037e5b59afd4ddede9577ae6a4adde38851091589ffc4efe8836c49ebf2
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

